{
 "title": "st_an",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Revenue (in lakhs) per category all-time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  product_category, \r\n  SUM(product_spend) / 100000.0 AS revenue_in_lakhs\r\nFROM transaction_items\r\nGROUP BY product_category\r\nORDER BY revenue_in_lakhs DESC;\r\n"
    }
   ]
  },
  {
   "title": "Total revenue today (in lakhs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COALESCE(SUM(transaction_amount), 0)/ 100000.0 AS total_revenue_today_lakhs\r\nFROM transactions\r\nWHERE timestamp::date = CURRENT_DATE\r\n  AND payment_status = 'successful';\r\n"
    }
   ]
  },
  {
   "title": "New users today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS new_users_today\r\nFROM users\r\nWHERE registered_at::date = CURRENT_DATE;\r\n"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_users FROM users;\r\n"
    }
   ]
  },
  {
   "title": "Most visited pages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT page, COUNT(*) AS visits\r\nFROM clickstream\r\nGROUP BY page\r\nORDER BY visits DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Most selling categories",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT product_category, SUM(quantity) AS total_sold\r\nFROM transaction_items\r\nGROUP BY product_category\r\nORDER BY total_sold DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Top locations by user count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TRIM(SPLIT_PART(location, ',', 2)) AS state,\r\n  COUNT(*) AS users_count\r\nFROM users\r\nWHERE location LIKE '%,%'  -- ensure there's a comma\r\nGROUP BY state\r\nORDER BY users_count DESC\r\nLIMIT 5;\r\n"
    }
   ]
  }
 ]
}